@WebApplication2_HostAddress = http://localhost:5107

GET {{WebApplication2_HostAddress}}/weatherforecast/
Accept: application/json

###

# @name login
POST {{WebApplication2_HostAddress}}/api/home/login
Content-Type: application/json

{
  "email": "nraina@gmail.com",
  "password": "54984"
}

###

GET {{WebApplication2_HostAddress}}/api/home/employee
Authorization: Bearer [AT]